name: libsodium
description: dart bindings for libsodium, a modern, easy-to-use crypto library.
version: 0.2.1
homepage: https://github.com/thelmuxkriovar/libsodium-dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  ffi: 2.1.0
  sqlite3_flutter_libs: 0.5.18

dev_dependencies:
  test: 1.24.9